services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_dev
    restart: always
    env_file:
      - .env
    depends_on:
      - cassandra
      - redis
    volumes:
      - ./:/app

  cassandra:
    image: cassandra:5.0
    restart: always
    env_file:
      - .env

  redis:
    image: redis:7.2-alpine3.20
    restart: always

  nginx:
    image: nginx:alpine3.19
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx/config.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
