services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_dev
    restart: always
    env_file:
      - .env
    depends_on:
      - cassandra
    ports:
      - 9000:9000
    volumes:
      - ./:/app

  cassandra:
    image: cassandra:5.0
    restart: always
    env_file:
      - .env
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data:
