services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_dev
    restart: always
    env_file:
      - .env
    depends_on:
      - cassandra
      - redis
    ports:
      - 9000:9000
    volumes:
      - ./:/app

  cassandra:
    image: cassandra:5.0
    restart: always
    env_file:
      - .env
    entrypoint: ["/init.sh"]
    volumes:
      - ./db/schema.cql:/schema.cql
      - ./db/init.sh:/init.sh

  redis:
    image: redis:7.2-alpine3.20
    restart: always

  nginx:
    image: nginx:alpine3.19
    restart: always
    volumes:
      - ./nginx/config.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
